// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnivSys.API.Data;

#nullable disable

namespace UnivSys.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106040003_AgregarTablasDeSeguridad")]
    partial class AgregarTablasDeSeguridad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnivSys.API.Models.Carrera", b =>
                {
                    b.Property<int>("IDCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCarrera"));

                    b.Property<string>("NombreCarrera")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDCarrera");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("UnivSys.API.Models.Estudiante", b =>
                {
                    b.Property<string>("IDEstudiante")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CarreraID")
                        .HasColumnType("int");

                    b.Property<int?>("CarreraIDCarrera")
                        .HasColumnType("int");

                    b.Property<bool>("EsBecado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsEgresado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre_s")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.HasKey("IDEstudiante");

                    b.HasIndex("CarreraID");

                    b.HasIndex("CarreraIDCarrera");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("UnivSys.API.Models.EstudianteBecado", b =>
                {
                    b.Property<string>("IDEstudiante")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<int>("PorcentajeBeca")
                        .HasColumnType("int");

                    b.HasKey("IDEstudiante");

                    b.ToTable("EstudiantesBecados");
                });

            modelBuilder.Entity("UnivSys.API.Models.EstudianteEgresado", b =>
                {
                    b.Property<string>("IDEstudiante")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime>("FechaEgreso")
                        .HasColumnType("DATE");

                    b.HasKey("IDEstudiante");

                    b.ToTable("EstudiantesEgresados");
                });

            modelBuilder.Entity("UnivSys.API.Models.HistorialAcademico", b =>
                {
                    b.Property<int>("IDRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRegistro"));

                    b.Property<decimal>("Calificacion")
                        .HasColumnType("DECIMAL(4, 2)");

                    b.Property<string>("IDEstudiante")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDRegistro");

                    b.HasIndex("IDEstudiante");

                    b.ToTable("HistorialAcademico");
                });

            modelBuilder.Entity("UnivSys.API.Models.Rol", b =>
                {
                    b.Property<int>("IDRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("UnivSys.API.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuario"));

                    b.Property<int>("IDRol")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDUsuario");

                    b.HasIndex("IDRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UnivSys.API.Models.Estudiante", b =>
                {
                    b.HasOne("UnivSys.API.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnivSys.API.Models.Carrera", null)
                        .WithMany("Estudiantes")
                        .HasForeignKey("CarreraIDCarrera");

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("UnivSys.API.Models.EstudianteBecado", b =>
                {
                    b.HasOne("UnivSys.API.Models.Estudiante", "Estudiante")
                        .WithOne("DetalleBecado")
                        .HasForeignKey("UnivSys.API.Models.EstudianteBecado", "IDEstudiante");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("UnivSys.API.Models.EstudianteEgresado", b =>
                {
                    b.HasOne("UnivSys.API.Models.Estudiante", "Estudiante")
                        .WithOne("DetalleEgresado")
                        .HasForeignKey("UnivSys.API.Models.EstudianteEgresado", "IDEstudiante");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("UnivSys.API.Models.HistorialAcademico", b =>
                {
                    b.HasOne("UnivSys.API.Models.Estudiante", "Estudiante")
                        .WithMany("Historial")
                        .HasForeignKey("IDEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("UnivSys.API.Models.Usuario", b =>
                {
                    b.HasOne("UnivSys.API.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IDRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("UnivSys.API.Models.Carrera", b =>
                {
                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("UnivSys.API.Models.Estudiante", b =>
                {
                    b.Navigation("DetalleBecado");

                    b.Navigation("DetalleEgresado");

                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
